import { type NextRequest, NextResponse } from "next/server"
import { createHash } from "crypto"
import { randomBytes } from "crypto"

// Simple password verification using Node.js crypto
// This matches the format generated by our password hash generator
function hashPassword(password: string): string {
  const salt = "wirya-admin-salt-2024"
  const hash = createHash("sha256")
    .update(password + salt)
    .digest("hex")
  return hash
}

function verifyPassword(password: string, storedHash: string): boolean {
  try {
    const generatedHash = hashPassword(password)
    return generatedHash === storedHash
  } catch (error) {
    console.error("[v0] Password verification error:", error)
    return false
  }
}

export async function POST(request: NextRequest) {
  try {
    const { email, password } = await request.json()

    console.log("[v0] Login attempt received")
    console.log("[v0] Email provided:", email ? "Yes" : "No")
    console.log("[v0] Password provided:", password ? "Yes" : "No")

    // Validate input
    if (!email || !password) {
      console.log("[v0] Validation failed: Missing email or password")
      return NextResponse.json({ error: "Email and password are required" }, { status: 400 })
    }

    // Get credentials from environment variables
    const adminEmail = process.env.ADMIN_EMAIL
    const adminPasswordHash = process.env.ADMIN_PASSWORD_HASH

    console.log("[v0] ADMIN_EMAIL exists:", !!adminEmail)
    console.log("[v0] ADMIN_PASSWORD_HASH exists:", !!adminPasswordHash)

    // Check if environment variables are set
    if (!adminEmail || !adminPasswordHash) {
      console.error("[v0] Missing ADMIN_EMAIL or ADMIN_PASSWORD_HASH environment variables")
      return NextResponse.json({ error: "Server configuration error. Please contact administrator." }, { status: 500 })
    }

    console.log("[v0] Verifying credentials...")
    console.log("[v0] Email match:", email === adminEmail)

    // Verify credentials
    if (email === adminEmail && verifyPassword(password, adminPasswordHash)) {
      console.log("[v0] Login successful")
      // Generate a simple session token
      const sessionToken = randomBytes(32).toString("hex")

      // In production, you should store this in a database with expiration
      // For now, we'll just return it and let the client store it

      return NextResponse.json(
        {
          success: true,
          token: sessionToken,
          message: "Login successful",
        },
        { status: 200 },
      )
    }

    console.log("[v0] Login failed: Invalid credentials")
    // Invalid credentials
    return NextResponse.json({ error: "Invalid email or password" }, { status: 401 })
  } catch (error) {
    console.error("[v0] Login error:", error)
    console.error("[v0] Error stack:", error instanceof Error ? error.stack : "No stack trace")
    console.error("[v0] Error message:", error instanceof Error ? error.message : String(error))
    return NextResponse.json({ error: "An error occurred during login" }, { status: 500 })
  }
}
